/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOverlaysRouteImport } from './routes/_authenticated/overlays'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDealershipsRouteImport } from './routes/_authenticated/dealerships'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBackdropsRouteImport } from './routes/_authenticated/backdrops'
import { Route as AuthenticatedVehiclesNewRouteImport } from './routes/_authenticated/vehicles.new'
import { Route as AuthenticatedVehiclesIdRouteImport } from './routes/_authenticated/vehicles.$id'
import { Route as AuthenticatedVehiclesIdEditRouteImport } from './routes/_authenticated/vehicles.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOverlaysRoute = AuthenticatedOverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealershipsRoute =
  AuthenticatedDealershipsRouteImport.update({
    id: '/dealerships',
    path: '/dealerships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackdropsRoute = AuthenticatedBackdropsRouteImport.update({
  id: '/backdrops',
  path: '/backdrops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVehiclesNewRoute =
  AuthenticatedVehiclesNewRouteImport.update({
    id: '/vehicles/new',
    path: '/vehicles/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVehiclesIdRoute = AuthenticatedVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVehiclesIdEditRoute =
  AuthenticatedVehiclesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedVehiclesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backdrops': typeof AuthenticatedBackdropsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealerships': typeof AuthenticatedDealershipsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/export': typeof AuthenticatedExportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/overlays': typeof AuthenticatedOverlaysRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdRouteWithChildren
  '/vehicles/new': typeof AuthenticatedVehiclesNewRoute
  '/vehicles/$id/edit': typeof AuthenticatedVehiclesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backdrops': typeof AuthenticatedBackdropsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealerships': typeof AuthenticatedDealershipsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/export': typeof AuthenticatedExportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/overlays': typeof AuthenticatedOverlaysRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdRouteWithChildren
  '/vehicles/new': typeof AuthenticatedVehiclesNewRoute
  '/vehicles/$id/edit': typeof AuthenticatedVehiclesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/backdrops': typeof AuthenticatedBackdropsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dealerships': typeof AuthenticatedDealershipsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/overlays': typeof AuthenticatedOverlaysRoute
  '/_authenticated/vehicles/$id': typeof AuthenticatedVehiclesIdRouteWithChildren
  '/_authenticated/vehicles/new': typeof AuthenticatedVehiclesNewRoute
  '/_authenticated/vehicles/$id/edit': typeof AuthenticatedVehiclesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backdrops'
    | '/dashboard'
    | '/dealerships'
    | '/documents'
    | '/export'
    | '/inventory'
    | '/overlays'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/vehicles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/backdrops'
    | '/dashboard'
    | '/dealerships'
    | '/documents'
    | '/export'
    | '/inventory'
    | '/overlays'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/vehicles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/backdrops'
    | '/_authenticated/dashboard'
    | '/_authenticated/dealerships'
    | '/_authenticated/documents'
    | '/_authenticated/export'
    | '/_authenticated/inventory'
    | '/_authenticated/overlays'
    | '/_authenticated/vehicles/$id'
    | '/_authenticated/vehicles/new'
    | '/_authenticated/vehicles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/overlays': {
      id: '/_authenticated/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof AuthenticatedOverlaysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dealerships': {
      id: '/_authenticated/dealerships'
      path: '/dealerships'
      fullPath: '/dealerships'
      preLoaderRoute: typeof AuthenticatedDealershipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backdrops': {
      id: '/_authenticated/backdrops'
      path: '/backdrops'
      fullPath: '/backdrops'
      preLoaderRoute: typeof AuthenticatedBackdropsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/new': {
      id: '/_authenticated/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof AuthenticatedVehiclesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/$id': {
      id: '/_authenticated/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof AuthenticatedVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/$id/edit': {
      id: '/_authenticated/vehicles/$id/edit'
      path: '/edit'
      fullPath: '/vehicles/$id/edit'
      preLoaderRoute: typeof AuthenticatedVehiclesIdEditRouteImport
      parentRoute: typeof AuthenticatedVehiclesIdRoute
    }
  }
}

interface AuthenticatedVehiclesIdRouteChildren {
  AuthenticatedVehiclesIdEditRoute: typeof AuthenticatedVehiclesIdEditRoute
}

const AuthenticatedVehiclesIdRouteChildren: AuthenticatedVehiclesIdRouteChildren =
  {
    AuthenticatedVehiclesIdEditRoute: AuthenticatedVehiclesIdEditRoute,
  }

const AuthenticatedVehiclesIdRouteWithChildren =
  AuthenticatedVehiclesIdRoute._addFileChildren(
    AuthenticatedVehiclesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBackdropsRoute: typeof AuthenticatedBackdropsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealershipsRoute: typeof AuthenticatedDealershipsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOverlaysRoute: typeof AuthenticatedOverlaysRoute
  AuthenticatedVehiclesIdRoute: typeof AuthenticatedVehiclesIdRouteWithChildren
  AuthenticatedVehiclesNewRoute: typeof AuthenticatedVehiclesNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBackdropsRoute: AuthenticatedBackdropsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealershipsRoute: AuthenticatedDealershipsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOverlaysRoute: AuthenticatedOverlaysRoute,
  AuthenticatedVehiclesIdRoute: AuthenticatedVehiclesIdRouteWithChildren,
  AuthenticatedVehiclesNewRoute: AuthenticatedVehiclesNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
