-- Admin-provisioned accounts, first-login containment, durable operation
-- reconciliation, and append-only security audit events.
--
-- Passwords are intentionally absent from every database object in this
-- migration. They are generated and returned once by trusted server code.

CREATE TABLE public.user_onboarding (
  profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  onboarding_method text NOT NULL DEFAULT 'pending'
    CHECK (onboarding_method IN ('pending', 'invitation', 'admin_provisioned', 'existing')),
  onboarding_state text NOT NULL DEFAULT 'password_change_required'
    CHECK (onboarding_state IN ('password_change_required', 'complete', 'blocked')),
  password_change_required boolean NOT NULL DEFAULT true,
  credential_issued_at timestamptz,
  password_changed_at timestamptz,
  completed_at timestamptz,
  issued_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (password_change_required AND onboarding_state <> 'complete')
    OR (NOT password_change_required AND onboarding_state = 'complete')
  )
);

-- Existing accounts predate temporary credentials and remain usable.
INSERT INTO public.user_onboarding (
  profile_id,
  onboarding_method,
  onboarding_state,
  password_change_required,
  password_changed_at,
  completed_at
)
SELECT id, 'existing', 'complete', false, now(), now()
FROM public.profiles;

CREATE TABLE public.user_account_operations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  operation_type text NOT NULL
    CHECK (operation_type IN ('admin_provision', 'temporary_password_reset')),
  idempotency_key uuid NOT NULL,
  target_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_email text NOT NULL,
  requested_full_name text,
  requested_role public.app_role,
  primary_dealership_id uuid REFERENCES public.dealerships(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'requested'
    CHECK (status IN (
      'requested', 'auth_pending', 'auth_updated', 'complete',
      'needs_reconciliation', 'failed', 'compensated'
    )),
  safe_error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (actor_profile_id, idempotency_key)
);

CREATE TABLE public.user_account_operation_dealerships (
  operation_id uuid NOT NULL REFERENCES public.user_account_operations(id) ON DELETE CASCADE,
  dealership_id uuid NOT NULL REFERENCES public.dealerships(id) ON DELETE RESTRICT,
  position smallint NOT NULL CHECK (position > 0),
  PRIMARY KEY (operation_id, dealership_id),
  UNIQUE (operation_id, position)
);

CREATE TABLE public.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL CHECK (length(event_type) BETWEEN 3 AND 120),
  actor_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  dealership_id uuid REFERENCES public.dealerships(id) ON DELETE SET NULL,
  request_id uuid,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX user_account_operations_target_profile_idx
  ON public.user_account_operations (target_profile_id, created_at DESC);
CREATE INDEX user_account_operations_reconciliation_idx
  ON public.user_account_operations (status, updated_at)
  WHERE status IN ('auth_pending', 'auth_updated', 'needs_reconciliation');
CREATE INDEX user_account_operation_dealerships_dealership_idx
  ON public.user_account_operation_dealerships (dealership_id, operation_id);
CREATE INDEX audit_events_actor_occurred_idx
  ON public.audit_events (actor_profile_id, occurred_at DESC);
CREATE INDEX audit_events_target_occurred_idx
  ON public.audit_events (target_profile_id, occurred_at DESC)
  WHERE target_profile_id IS NOT NULL;
CREATE INDEX audit_events_dealership_occurred_idx
  ON public.audit_events (dealership_id, occurred_at DESC)
  WHERE dealership_id IS NOT NULL;

ALTER TABLE public.user_onboarding ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_account_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_account_operation_dealerships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.user_onboarding FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.user_account_operations FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.user_account_operation_dealerships FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.audit_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.audit_events_id_seq FROM PUBLIC, anon, authenticated;

GRANT SELECT ON public.user_onboarding TO authenticated;
GRANT SELECT ON public.audit_events TO authenticated;
GRANT ALL ON public.user_onboarding TO service_role;
GRANT ALL ON public.user_account_operations TO service_role;
GRANT ALL ON public.user_account_operation_dealerships TO service_role;
GRANT ALL ON public.audit_events TO service_role;
GRANT ALL ON SEQUENCE public.audit_events_id_seq TO service_role;

CREATE POLICY "Users view own onboarding state"
ON public.user_onboarding FOR SELECT TO authenticated
USING (
  profile_id = (SELECT auth.uid())
  AND (SELECT private.current_user_is_active())
);

CREATE POLICY "Authorized administrators view scoped audit events"
ON public.audit_events FOR SELECT TO authenticated
USING (
  (SELECT private.current_user_is_active_owner())
  OR (
    dealership_id IS NOT NULL
    AND private.current_user_is_dealership_admin(dealership_id)
  )
);

CREATE OR REPLACE FUNCTION private.current_user_has_completed_onboarding()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_onboarding AS uo
    WHERE uo.profile_id = (SELECT auth.uid())
      AND uo.onboarding_state = 'complete'
      AND uo.password_change_required = false
  );
$$;

-- Redefine every root authorization helper so a still-valid JWT cannot access
-- business data until a temporary password is replaced.
CREATE OR REPLACE FUNCTION private.current_user_is_active_owner()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles AS p
    JOIN public.user_onboarding AS uo ON uo.profile_id = p.id
    WHERE p.id = (SELECT auth.uid())
      AND p.status = 'active'
      AND p.role = 'owner'::public.app_role
      AND uo.onboarding_state = 'complete'
      AND uo.password_change_required = false
  );
$$;

CREATE OR REPLACE FUNCTION private.current_user_dealership_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT p.dealership_id
  FROM public.profiles AS p
  JOIN public.user_onboarding AS uo ON uo.profile_id = p.id
  JOIN public.dealerships AS d ON d.id = p.dealership_id
  WHERE p.id = (SELECT auth.uid())
    AND p.status = 'active'
    AND p.role <> 'owner'::public.app_role
    AND uo.onboarding_state = 'complete'
    AND uo.password_change_required = false
    AND d.status IN ('active', 'trial')
    AND d.subscription_status = 'active'
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION private.current_user_has_active_membership(_dealership_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT private.current_user_is_active_owner())
    OR EXISTS (
      SELECT 1
      FROM public.profiles AS p
      JOIN public.user_onboarding AS uo ON uo.profile_id = p.id
      JOIN public.profile_dealerships AS pd ON pd.profile_id = p.id
      JOIN public.dealerships AS d ON d.id = pd.dealership_id
      WHERE p.id = (SELECT auth.uid())
        AND p.status = 'active'
        AND p.role <> 'owner'::public.app_role
        AND uo.onboarding_state = 'complete'
        AND uo.password_change_required = false
        AND pd.dealership_id = _dealership_id
        AND (
          p.role = 'dealer_admin'::public.app_role
          OR p.dealership_id = pd.dealership_id
        )
        AND d.status IN ('active', 'trial')
        AND d.subscription_status = 'active'
    );
$$;

CREATE OR REPLACE FUNCTION private.current_user_is_dealership_admin(_dealership_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT private.current_user_is_active_owner())
    OR EXISTS (
      SELECT 1
      FROM public.profiles AS p
      JOIN public.user_onboarding AS uo ON uo.profile_id = p.id
      JOIN public.profile_dealerships AS pd ON pd.profile_id = p.id
      JOIN public.dealerships AS d ON d.id = pd.dealership_id
      WHERE p.id = (SELECT auth.uid())
        AND p.status = 'active'
        AND p.role = 'dealer_admin'::public.app_role
        AND uo.onboarding_state = 'complete'
        AND uo.password_change_required = false
        AND pd.dealership_id = _dealership_id
        AND d.status IN ('active', 'trial')
        AND d.subscription_status = 'active'
    );
$$;

REVOKE ALL ON FUNCTION private.current_user_has_completed_onboarding()
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION private.current_user_has_completed_onboarding() TO authenticated;

-- Auth creates only a non-privileged placeholder. No role or dealership value
-- from user-editable metadata is trusted.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.email, ''),
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    'staff'::public.app_role
  );

  INSERT INTO public.user_onboarding (
    profile_id,
    onboarding_method,
    onboarding_state,
    password_change_required
  ) VALUES (NEW.id, 'pending', 'password_change_required', true);

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION private.actor_is_active_owner(_actor_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles AS p
    JOIN public.user_onboarding AS uo ON uo.profile_id = p.id
    WHERE p.id = _actor_id
      AND p.status = 'active'
      AND p.role = 'owner'::public.app_role
      AND uo.onboarding_state = 'complete'
      AND uo.password_change_required = false
  );
$$;

CREATE OR REPLACE FUNCTION private.actor_is_active_dealer_admin_for(
  _actor_id uuid,
  _dealership_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles AS p
    JOIN public.user_onboarding AS uo ON uo.profile_id = p.id
    JOIN public.profile_dealerships AS pd ON pd.profile_id = p.id
    JOIN public.dealerships AS d ON d.id = pd.dealership_id
    WHERE p.id = _actor_id
      AND p.status = 'active'
      AND p.role = 'dealer_admin'::public.app_role
      AND uo.onboarding_state = 'complete'
      AND uo.password_change_required = false
      AND pd.dealership_id = _dealership_id
      AND d.status IN ('active', 'trial')
      AND d.subscription_status = 'active'
  );
$$;

CREATE OR REPLACE FUNCTION private.validate_dealer_account_scope(
  _actor_id uuid,
  _role public.app_role,
  _dealership_ids uuid[]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  assignment_count integer := COALESCE(cardinality(_dealership_ids), 0);
  valid_count integer;
BEGIN
  IF _role NOT IN ('dealer_admin'::public.app_role, 'staff'::public.app_role) THEN
    RAISE EXCEPTION 'Only dealer administrator and staff accounts may be provisioned.';
  END IF;
  IF assignment_count = 0 OR assignment_count > 100
     OR array_position(_dealership_ids, NULL) IS NOT NULL THEN
    RAISE EXCEPTION 'Select between one and 100 active dealerships.';
  END IF;
  IF _role = 'staff'::public.app_role AND assignment_count <> 1 THEN
    RAISE EXCEPTION 'Staff accounts must belong to exactly one dealership.';
  END IF;
  IF (SELECT count(DISTINCT id) FROM unnest(_dealership_ids) AS id) <> assignment_count THEN
    RAISE EXCEPTION 'Duplicate dealership assignments are not allowed.';
  END IF;

  SELECT count(*) INTO valid_count
  FROM public.dealerships AS d
  WHERE d.id = ANY (_dealership_ids)
    AND d.status IN ('active', 'trial')
    AND d.subscription_status = 'active';
  IF valid_count <> assignment_count THEN
    RAISE EXCEPTION 'Every assigned dealership must be active.';
  END IF;

  IF (SELECT private.actor_is_active_owner(_actor_id)) THEN
    RETURN;
  END IF;
  IF _role <> 'staff'::public.app_role OR assignment_count <> 1
     OR NOT (SELECT private.actor_is_active_dealer_admin_for(_actor_id, _dealership_ids[1])) THEN
    RAISE EXCEPTION 'Forbidden';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.begin_user_provisioning_operation(
  _actor_id uuid,
  _idempotency_key uuid,
  _email text,
  _full_name text,
  _role public.app_role,
  _dealership_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  existing public.user_account_operations%ROWTYPE;
  operation_id uuid;
  normalized_email text := lower(btrim(_email));
BEGIN
  IF _idempotency_key IS NULL THEN
    RAISE EXCEPTION 'An idempotency key is required.';
  END IF;
  IF normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
     OR length(normalized_email) > 255 THEN
    RAISE EXCEPTION 'Enter a valid email address.';
  END IF;
  IF NULLIF(btrim(_full_name), '') IS NULL OR length(btrim(_full_name)) > 120 THEN
    RAISE EXCEPTION 'Enter a valid full name.';
  END IF;
  PERFORM private.validate_dealer_account_scope(_actor_id, _role, _dealership_ids);

  SELECT * INTO existing
  FROM public.user_account_operations
  WHERE actor_profile_id = _actor_id AND idempotency_key = _idempotency_key
  FOR UPDATE;

  IF FOUND THEN
    IF existing.operation_type <> 'admin_provision'
       OR existing.target_email <> normalized_email
       OR existing.requested_full_name <> btrim(_full_name)
       OR existing.requested_role <> _role
       OR NOT (
         SELECT COALESCE(array_agg(uad.dealership_id ORDER BY uad.position), '{}'::uuid[])
         FROM public.user_account_operation_dealerships AS uad
         WHERE uad.operation_id = existing.id
       ) = _dealership_ids THEN
      RAISE EXCEPTION 'This idempotency key belongs to a different request.';
    END IF;
    RETURN jsonb_build_object(
      'operation_id', existing.id,
      'status', existing.status,
      'target_profile_id', existing.target_profile_id
    );
  END IF;

  IF EXISTS (SELECT 1 FROM public.profiles WHERE lower(email) = normalized_email) THEN
    RAISE EXCEPTION 'A user with that email already exists.';
  END IF;

  INSERT INTO public.user_account_operations (
    actor_profile_id, operation_type, idempotency_key, target_email,
    requested_full_name, requested_role, primary_dealership_id
  ) VALUES (
    _actor_id, 'admin_provision', _idempotency_key, normalized_email,
    btrim(_full_name), _role, _dealership_ids[1]
  ) RETURNING id INTO operation_id;

  INSERT INTO public.user_account_operation_dealerships (
    operation_id, dealership_id, position
  )
  SELECT operation_id, assignment.dealership_id, assignment.position::smallint
  FROM unnest(_dealership_ids) WITH ORDINALITY AS assignment(dealership_id, position);

  RETURN jsonb_build_object('operation_id', operation_id, 'status', 'requested');
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_user_account_operation(
  _actor_id uuid,
  _operation_id uuid,
  _status text,
  _target_profile_id uuid DEFAULT NULL,
  _safe_error_code text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF _status NOT IN ('auth_pending', 'auth_updated', 'needs_reconciliation', 'failed', 'compensated') THEN
    RAISE EXCEPTION 'Invalid operation status.';
  END IF;
  UPDATE public.user_account_operations
  SET status = _status,
      target_profile_id = COALESCE(_target_profile_id, target_profile_id),
      safe_error_code = left(_safe_error_code, 80),
      updated_at = now()
  WHERE id = _operation_id
    AND actor_profile_id = _actor_id
    AND status <> 'complete';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Operation not found or already complete.';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_user_provisioning_operation(
  _actor_id uuid,
  _operation_id uuid,
  _auth_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  operation public.user_account_operations%ROWTYPE;
  dealership_ids uuid[];
  target public.profiles%ROWTYPE;
BEGIN
  SELECT * INTO operation
  FROM public.user_account_operations
  WHERE id = _operation_id AND actor_profile_id = _actor_id
  FOR UPDATE;
  IF NOT FOUND OR operation.operation_type <> 'admin_provision' THEN
    RAISE EXCEPTION 'Provisioning operation not found.';
  END IF;

  SELECT COALESCE(array_agg(dealership_id ORDER BY position), '{}'::uuid[])
  INTO dealership_ids
  FROM public.user_account_operation_dealerships
  WHERE operation_id = operation.id;

  PERFORM private.validate_dealer_account_scope(_actor_id, operation.requested_role, dealership_ids);

  IF operation.status = 'complete' THEN
    IF operation.target_profile_id <> _auth_user_id THEN
      RAISE EXCEPTION 'Operation target mismatch.';
    END IF;
    RETURN jsonb_build_object('ok', true, 'reconciled', true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM auth.users AS u
    WHERE u.id = _auth_user_id AND lower(u.email) = operation.target_email
  ) THEN
    RAISE EXCEPTION 'Auth user does not match the operation.';
  END IF;

  SELECT * INTO target FROM public.profiles WHERE id = _auth_user_id FOR UPDATE;
  IF NOT FOUND OR target.role <> 'staff'::public.app_role OR target.dealership_id IS NOT NULL THEN
    RAISE EXCEPTION 'Provisioning target is not a pristine placeholder profile.';
  END IF;

  UPDATE public.profiles
  SET full_name = operation.requested_full_name,
      role = operation.requested_role,
      dealership_id = dealership_ids[1],
      status = 'active'
  WHERE id = _auth_user_id;

  DELETE FROM public.profile_dealerships WHERE profile_id = _auth_user_id;
  INSERT INTO public.profile_dealerships (profile_id, dealership_id)
  SELECT _auth_user_id, id FROM unnest(dealership_ids) AS id;

  INSERT INTO public.user_onboarding (
    profile_id, onboarding_method, onboarding_state,
    password_change_required, credential_issued_at, issued_by, updated_at
  ) VALUES (
    _auth_user_id, 'admin_provisioned', 'password_change_required',
    true, now(), _actor_id, now()
  )
  ON CONFLICT (profile_id) DO UPDATE SET
    onboarding_method = 'admin_provisioned',
    onboarding_state = 'password_change_required',
    password_change_required = true,
    credential_issued_at = now(),
    password_changed_at = NULL,
    completed_at = NULL,
    issued_by = _actor_id,
    updated_at = now();

  UPDATE public.user_account_operations
  SET target_profile_id = _auth_user_id,
      status = 'complete',
      safe_error_code = NULL,
      updated_at = now(),
      completed_at = now()
  WHERE id = operation.id;

  INSERT INTO public.audit_events (
    event_type, actor_profile_id, target_profile_id, dealership_id, request_id, payload
  ) VALUES (
    'user.account_provisioned', _actor_id, _auth_user_id, dealership_ids[1],
    operation.idempotency_key,
    jsonb_build_object('role', operation.requested_role, 'dealership_count', cardinality(dealership_ids))
  );

  RETURN jsonb_build_object('ok', true, 'reconciled', false);
END;
$$;

CREATE OR REPLACE FUNCTION public.begin_temporary_password_reset_operation(
  _actor_id uuid,
  _idempotency_key uuid,
  _target_profile_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target public.profiles%ROWTYPE;
  existing public.user_account_operations%ROWTYPE;
  target_dealership_id uuid;
  operation_id uuid;
BEGIN
  IF _actor_id = _target_profile_id THEN
    RAISE EXCEPTION 'You cannot reset your own credentials here.';
  END IF;
  SELECT * INTO target FROM public.profiles WHERE id = _target_profile_id;
  IF NOT FOUND OR target.status <> 'active' OR target.role = 'owner'::public.app_role THEN
    RAISE EXCEPTION 'This account is not eligible for an administrator reset.';
  END IF;

  SELECT pd.dealership_id INTO target_dealership_id
  FROM public.profile_dealerships AS pd
  JOIN public.dealerships AS d ON d.id = pd.dealership_id
  WHERE pd.profile_id = target.id
    AND d.status IN ('active', 'trial')
    AND d.subscription_status = 'active'
  ORDER BY (pd.dealership_id = target.dealership_id) DESC
  LIMIT 1;
  IF target_dealership_id IS NULL THEN
    RAISE EXCEPTION 'The target account has no active dealership.';
  END IF;

  IF NOT (SELECT private.actor_is_active_owner(_actor_id)) THEN
    IF target.role <> 'staff'::public.app_role
       OR NOT (SELECT private.actor_is_active_dealer_admin_for(_actor_id, target_dealership_id)) THEN
      RAISE EXCEPTION 'Forbidden';
    END IF;
  END IF;

  SELECT * INTO existing
  FROM public.user_account_operations
  WHERE actor_profile_id = _actor_id AND idempotency_key = _idempotency_key
  FOR UPDATE;
  IF FOUND THEN
    IF existing.operation_type <> 'temporary_password_reset'
       OR existing.target_profile_id <> _target_profile_id THEN
      RAISE EXCEPTION 'This idempotency key belongs to a different request.';
    END IF;
    RETURN jsonb_build_object('operation_id', existing.id, 'status', existing.status);
  END IF;

  INSERT INTO public.user_account_operations (
    actor_profile_id, operation_type, idempotency_key, target_profile_id,
    target_email, requested_role, primary_dealership_id
  ) VALUES (
    _actor_id, 'temporary_password_reset', _idempotency_key, target.id,
    lower(target.email), target.role, target_dealership_id
  ) RETURNING id INTO operation_id;

  RETURN jsonb_build_object('operation_id', operation_id, 'status', 'requested');
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_temporary_password_reset_operation(
  _actor_id uuid,
  _operation_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  operation public.user_account_operations%ROWTYPE;
  target public.profiles%ROWTYPE;
BEGIN
  SELECT * INTO operation
  FROM public.user_account_operations
  WHERE id = _operation_id AND actor_profile_id = _actor_id
  FOR UPDATE;
  IF NOT FOUND OR operation.operation_type <> 'temporary_password_reset' THEN
    RAISE EXCEPTION 'Password reset operation not found.';
  END IF;

  SELECT * INTO target FROM public.profiles WHERE id = operation.target_profile_id;
  IF NOT FOUND OR target.status <> 'active' OR target.role = 'owner'::public.app_role THEN
    RAISE EXCEPTION 'This account is no longer eligible for reset.';
  END IF;
  IF NOT (SELECT private.actor_is_active_owner(_actor_id)) THEN
    IF target.role <> 'staff'::public.app_role
       OR NOT (SELECT private.actor_is_active_dealer_admin_for(_actor_id, operation.primary_dealership_id)) THEN
      RAISE EXCEPTION 'Forbidden';
    END IF;
  END IF;

  IF operation.status = 'complete' THEN
    RETURN jsonb_build_object('ok', true, 'reconciled', true);
  END IF;

  UPDATE public.user_onboarding
  SET onboarding_method = 'admin_provisioned',
      onboarding_state = 'password_change_required',
      password_change_required = true,
      credential_issued_at = now(),
      password_changed_at = NULL,
      completed_at = NULL,
      issued_by = _actor_id,
      updated_at = now()
  WHERE profile_id = target.id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Target onboarding state is missing.';
  END IF;

  UPDATE public.user_account_operations
  SET status = 'complete', safe_error_code = NULL,
      updated_at = now(), completed_at = now()
  WHERE id = operation.id;

  INSERT INTO public.audit_events (
    event_type, actor_profile_id, target_profile_id, dealership_id, request_id, payload
  ) VALUES (
    'user.temporary_password_reset', _actor_id, target.id,
    operation.primary_dealership_id, operation.idempotency_key,
    jsonb_build_object('role', target.role)
  );

  RETURN jsonb_build_object('ok', true, 'reconciled', false);
END;
$$;

-- Fail closed when the Auth provider response or the final database write is
-- uncertain. This never asserts that the credential changed; it only blocks
-- business-data access until an administrator performs a fresh reset or an
-- operator reconciles the durable operation record.
CREATE OR REPLACE FUNCTION public.contain_temporary_password_reset_operation(
  _actor_id uuid,
  _operation_id uuid,
  _safe_error_code text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  operation public.user_account_operations%ROWTYPE;
  target public.profiles%ROWTYPE;
BEGIN
  SELECT * INTO operation
  FROM public.user_account_operations
  WHERE id = _operation_id AND actor_profile_id = _actor_id
  FOR UPDATE;
  IF NOT FOUND OR operation.operation_type <> 'temporary_password_reset' THEN
    RAISE EXCEPTION 'Password reset operation not found.';
  END IF;

  SELECT * INTO target FROM public.profiles WHERE id = operation.target_profile_id;
  IF NOT FOUND OR target.status <> 'active' OR target.role = 'owner'::public.app_role THEN
    RAISE EXCEPTION 'This account is no longer eligible for reset.';
  END IF;
  IF NOT (SELECT private.actor_is_active_owner(_actor_id)) THEN
    IF target.role <> 'staff'::public.app_role
       OR NOT (SELECT private.actor_is_active_dealer_admin_for(_actor_id, operation.primary_dealership_id)) THEN
      RAISE EXCEPTION 'Forbidden';
    END IF;
  END IF;

  UPDATE public.user_onboarding
  SET onboarding_method = 'admin_provisioned',
      onboarding_state = 'password_change_required',
      password_change_required = true,
      password_changed_at = NULL,
      completed_at = NULL,
      issued_by = _actor_id,
      updated_at = now()
  WHERE profile_id = target.id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Target onboarding state is missing.'; END IF;

  UPDATE public.user_account_operations
  SET status = 'needs_reconciliation',
      safe_error_code = left(coalesce(_safe_error_code, 'unknown'), 80),
      updated_at = now()
  WHERE id = operation.id AND status <> 'complete';

  INSERT INTO public.audit_events (
    event_type, actor_profile_id, target_profile_id, dealership_id, request_id, payload
  ) VALUES (
    'user.temporary_password_reset_contained', _actor_id, target.id,
    operation.primary_dealership_id, operation.idempotency_key,
    jsonb_build_object('reason', left(coalesce(_safe_error_code, 'unknown'), 80))
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_temporary_password_onboarding(_actor_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF _actor_id IS NULL OR _actor_id <> (SELECT auth.uid()) THEN
    -- Service-role RPCs have no auth.uid(); trusted server passes the identity
    -- it just verified with Auth. Permit that context but reject mismatched JWTs.
    IF (SELECT auth.uid()) IS NOT NULL THEN
      RAISE EXCEPTION 'Forbidden';
    END IF;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = _actor_id AND status = 'active'
  ) THEN
    RAISE EXCEPTION 'Account unavailable.';
  END IF;

  UPDATE public.user_onboarding
  SET onboarding_state = 'complete',
      password_change_required = false,
      password_changed_at = now(),
      completed_at = now(),
      updated_at = now()
  WHERE profile_id = _actor_id
    AND password_change_required = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Password change is not required.';
  END IF;

  INSERT INTO public.audit_events (event_type, actor_profile_id, target_profile_id, payload)
  VALUES ('user.temporary_password_changed', _actor_id, _actor_id, '{}'::jsonb);
END;
$$;

-- Invitation onboarding becomes complete only after accept_invitation validates
-- the invitation and assigns the account. Existing invitation behavior remains.
CREATE OR REPLACE FUNCTION public.accept_invitation(_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  inv public.user_invitations%ROWTYPE;
  current_email text;
  current_profile public.profiles%ROWTYPE;
BEGIN
  IF (SELECT auth.uid()) IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT u.email INTO current_email FROM auth.users AS u WHERE u.id = (SELECT auth.uid());
  SELECT * INTO inv FROM public.user_invitations WHERE token = _token FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Invitation not found'; END IF;
  IF inv.status <> 'pending' OR inv.expires_at < now() THEN
    RAISE EXCEPTION 'Invitation is no longer valid';
  END IF;
  IF current_email IS NULL OR lower(inv.email) <> lower(current_email) THEN
    RAISE EXCEPTION 'Invitation email does not match signed-in user';
  END IF;
  IF inv.role NOT IN ('dealer_admin', 'staff') OR inv.dealership_id IS NULL THEN
    RAISE EXCEPTION 'Invitation role or dealership is invalid';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.dealerships AS d
    WHERE d.id = inv.dealership_id
      AND d.status IN ('active', 'trial')
      AND d.subscription_status = 'active'
  ) THEN RAISE EXCEPTION 'Dealership is not active'; END IF;

  SELECT * INTO current_profile FROM public.profiles
  WHERE id = (SELECT auth.uid()) FOR UPDATE;
  IF NOT FOUND OR current_profile.role <> 'staff'::public.app_role
     OR current_profile.dealership_id IS NOT NULL THEN
    RAISE EXCEPTION 'Existing account cannot accept this invitation';
  END IF;

  UPDATE public.profiles
  SET role = inv.role::public.app_role,
      dealership_id = inv.dealership_id,
      full_name = COALESCE(NULLIF(inv.full_name, ''), full_name),
      status = 'active'
  WHERE id = (SELECT auth.uid());
  UPDATE public.user_onboarding
  SET onboarding_method = 'invitation', onboarding_state = 'complete',
      password_change_required = false, password_changed_at = now(),
      completed_at = now(), updated_at = now()
  WHERE profile_id = (SELECT auth.uid());
  UPDATE public.user_invitations SET status = 'accepted', accepted_at = now() WHERE id = inv.id;
  INSERT INTO public.audit_events (
    event_type, actor_profile_id, target_profile_id, dealership_id, payload
  ) VALUES (
    'user.invitation_accepted', (SELECT auth.uid()), (SELECT auth.uid()),
    inv.dealership_id, jsonb_build_object('role', inv.role)
  );
  RETURN jsonb_build_object('ok', true, 'dealership_id', inv.dealership_id);
END;
$$;

-- Public RPC execution is denied by default in PostgreSQL; make the intended
-- service-only surface explicit and leave invitation acceptance user-scoped.
REVOKE ALL ON FUNCTION private.actor_is_active_owner(uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.actor_is_active_dealer_admin_for(uuid, uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.validate_dealer_account_scope(uuid, public.app_role, uuid[]) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.begin_user_provisioning_operation(uuid, uuid, text, text, public.app_role, uuid[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.mark_user_account_operation(uuid, uuid, text, uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finalize_user_provisioning_operation(uuid, uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.begin_temporary_password_reset_operation(uuid, uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finalize_temporary_password_reset_operation(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.contain_temporary_password_reset_operation(uuid, uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_temporary_password_onboarding(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.begin_user_provisioning_operation(uuid, uuid, text, text, public.app_role, uuid[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_user_account_operation(uuid, uuid, text, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.finalize_user_provisioning_operation(uuid, uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.begin_temporary_password_reset_operation(uuid, uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.finalize_temporary_password_reset_operation(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.contain_temporary_password_reset_operation(uuid, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_temporary_password_onboarding(uuid) TO service_role;
REVOKE ALL ON FUNCTION public.accept_invitation(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.accept_invitation(text) TO authenticated;

-- Expand the existing account-access mutation to the approved administrator
-- scope. Owner access stays global; dealer administrators may edit only staff
-- in one of their currently active assigned dealerships.
CREATE OR REPLACE FUNCTION public.admin_update_user_account_access(
  _actor_user_id uuid,
  _target_user_id uuid,
  _full_name text,
  _role public.app_role,
  _dealership_ids uuid[]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target_role public.app_role;
  target_primary uuid;
  assignment_count integer := COALESCE(cardinality(_dealership_ids), 0);
BEGIN
  IF _actor_user_id = _target_user_id THEN
    RAISE EXCEPTION 'Use profile settings to change your own name.';
  END IF;
  SELECT role, dealership_id INTO target_role, target_primary
  FROM public.profiles WHERE id = _target_user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'User not found'; END IF;
  IF target_role = 'owner'::public.app_role THEN
    RAISE EXCEPTION 'Owner roles cannot be changed through user administration.';
  END IF;
  PERFORM private.validate_dealer_account_scope(_actor_user_id, _role, _dealership_ids);
  IF NOT (SELECT private.actor_is_active_owner(_actor_user_id)) THEN
    IF target_role <> 'staff'::public.app_role OR _role <> 'staff'::public.app_role
       OR assignment_count <> 1
       OR NOT (SELECT private.actor_is_active_dealer_admin_for(_actor_user_id, target_primary)) THEN
      RAISE EXCEPTION 'Forbidden';
    END IF;
  END IF;
  IF NULLIF(btrim(_full_name), '') IS NULL OR length(btrim(_full_name)) > 120 THEN
    RAISE EXCEPTION 'Enter a valid full name.';
  END IF;

  UPDATE public.profiles
  SET full_name = btrim(_full_name), role = _role, dealership_id = _dealership_ids[1]
  WHERE id = _target_user_id;
  DELETE FROM public.profile_dealerships WHERE profile_id = _target_user_id;
  INSERT INTO public.profile_dealerships (profile_id, dealership_id)
  SELECT _target_user_id, id FROM unnest(_dealership_ids) AS id;

  INSERT INTO public.audit_events (
    event_type, actor_profile_id, target_profile_id, dealership_id, payload
  ) VALUES (
    'user.access_updated', _actor_user_id, _target_user_id, _dealership_ids[1],
    jsonb_build_object('role', _role, 'dealership_count', cardinality(_dealership_ids))
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user_activation(
  _actor_id uuid,
  _target_profile_id uuid,
  _status text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target public.profiles%ROWTYPE;
BEGIN
  IF _status NOT IN ('active', 'deactivated') THEN RAISE EXCEPTION 'Invalid status.'; END IF;
  IF _actor_id = _target_profile_id THEN RAISE EXCEPTION 'You cannot change your own activation.'; END IF;
  SELECT * INTO target FROM public.profiles WHERE id = _target_profile_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'User not found'; END IF;
  IF target.role = 'owner'::public.app_role THEN RAISE EXCEPTION 'Owner activation is protected.'; END IF;

  IF NOT (SELECT private.actor_is_active_owner(_actor_id)) THEN
    IF target.role <> 'staff'::public.app_role
       OR target.dealership_id IS NULL
       OR NOT (SELECT private.actor_is_active_dealer_admin_for(_actor_id, target.dealership_id)) THEN
      RAISE EXCEPTION 'Forbidden';
    END IF;
  END IF;
  IF _status = 'active' AND NOT EXISTS (
    SELECT 1 FROM public.dealerships AS d
    WHERE d.id = target.dealership_id
      AND d.status IN ('active', 'trial')
      AND d.subscription_status = 'active'
  ) THEN RAISE EXCEPTION 'The assigned dealership is not active.'; END IF;

  UPDATE public.profiles SET status = _status WHERE id = target.id;
  INSERT INTO public.audit_events (
    event_type, actor_profile_id, target_profile_id, dealership_id, payload
  ) VALUES (
    CASE WHEN _status = 'active' THEN 'user.reactivated' ELSE 'user.deactivated' END,
    _actor_id, target.id, target.dealership_id, jsonb_build_object('status', _status)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_update_user_account_access(
  uuid, uuid, text, public.app_role, uuid[]
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_user_account_access(
  uuid, uuid, text, public.app_role, uuid[]
) TO service_role;
REVOKE ALL ON FUNCTION public.admin_set_user_activation(uuid, uuid, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_activation(uuid, uuid, text) TO service_role;
