-- Durable operational activity, versioned payout rules, accounting records,
-- and provider-neutral integration/publication status. No external provider is
-- connected by this migration and no credential values belong in these rows.

CREATE TABLE public.activity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  dealership_id uuid NOT NULL REFERENCES public.dealerships(id) ON DELETE CASCADE,
  vehicle_id uuid REFERENCES public.vehicles(id) ON DELETE SET NULL,
  photo_shoot_id uuid REFERENCES public.photo_capture_sessions(id) ON DELETE SET NULL,
  actor_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_type text NOT NULL CHECK (event_type ~ '^[a-z][a-z0-9_.-]{2,119}$'),
  description text NOT NULL CHECK (length(description) BETWEEN 1 AND 300),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(metadata) = 'object' AND octet_length(metadata::text) <= 65536),
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX activity_events_dealership_date_idx
  ON public.activity_events (dealership_id, occurred_at DESC, id DESC);
CREATE INDEX activity_events_employee_date_idx
  ON public.activity_events (actor_profile_id, occurred_at DESC, id DESC)
  WHERE actor_profile_id IS NOT NULL;
CREATE INDEX activity_events_vehicle_date_idx
  ON public.activity_events (vehicle_id, occurred_at DESC, id DESC)
  WHERE vehicle_id IS NOT NULL;
CREATE INDEX activity_events_shoot_idx
  ON public.activity_events (photo_shoot_id, occurred_at DESC)
  WHERE photo_shoot_id IS NOT NULL;

CREATE TABLE public.payout_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dealership_id uuid NOT NULL REFERENCES public.dealerships(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 160),
  task_type text NOT NULL CHECK (task_type IN ('photo_shoot', 'video', 'exterior_360', 'interior_360', 'reshoot', 'audit', 'manual')),
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  version integer NOT NULL CHECK (version > 0),
  effective_from date NOT NULL,
  effective_to date,
  active boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(config) = 'object' AND octet_length(config::text) <= 65536),
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_to IS NULL OR effective_to >= effective_from),
  UNIQUE (dealership_id, task_type, version)
);

CREATE INDEX payout_rules_effective_idx
  ON public.payout_rules (dealership_id, task_type, effective_from DESC)
  WHERE active;
CREATE INDEX payout_rules_created_by_idx
  ON public.payout_rules (created_by, created_at DESC) WHERE created_by IS NOT NULL;

CREATE TABLE public.payout_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dealership_id uuid NOT NULL REFERENCES public.dealerships(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  employee_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  vehicle_id uuid REFERENCES public.vehicles(id) ON DELETE SET NULL,
  photo_shoot_id uuid REFERENCES public.photo_capture_sessions(id) ON DELETE SET NULL,
  activity_event_id bigint REFERENCES public.activity_events(id) ON DELETE SET NULL,
  task_type text NOT NULL CHECK (task_type IN ('photo_shoot', 'video', 'exterior_360', 'interior_360', 'reshoot', 'audit', 'manual')),
  work_date date NOT NULL,
  amount numeric(12,2) NOT NULL,
  currency text NOT NULL DEFAULT 'USD' CHECK (currency ~ '^[A-Z]{3}$'),
  rule_id uuid REFERENCES public.payout_rules(id) ON DELETE SET NULL,
  rule_snapshot jsonb NOT NULL
    CHECK (jsonb_typeof(rule_snapshot) = 'object' AND octet_length(rule_snapshot::text) <= 65536),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid', 'void')),
  approved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_at timestamptz,
  paid_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  paid_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status IN ('approved','paid') AND approved_at IS NOT NULL AND approved_by IS NOT NULL) OR status IN ('pending','void')),
  CHECK ((status = 'paid' AND paid_at IS NOT NULL AND paid_by IS NOT NULL) OR status <> 'paid')
);

CREATE UNIQUE INDEX payout_entries_shoot_task_once_idx
  ON public.payout_entries (photo_shoot_id, task_type)
  WHERE photo_shoot_id IS NOT NULL AND status <> 'void';
CREATE INDEX payout_entries_report_idx
  ON public.payout_entries (dealership_id, work_date DESC, employee_id, status);
CREATE INDEX payout_entries_employee_idx
  ON public.payout_entries (employee_id, work_date DESC, status);
CREATE INDEX payout_entries_rule_idx
  ON public.payout_entries (rule_id) WHERE rule_id IS NOT NULL;
CREATE INDEX payout_entries_activity_idx
  ON public.payout_entries (activity_event_id) WHERE activity_event_id IS NOT NULL;
CREATE INDEX payout_entries_approved_by_idx
  ON public.payout_entries (approved_by, approved_at DESC) WHERE approved_by IS NOT NULL;
CREATE INDEX payout_entries_paid_by_idx
  ON public.payout_entries (paid_by, paid_at DESC) WHERE paid_by IS NOT NULL;

CREATE TABLE public.integration_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  dealership_id uuid REFERENCES public.dealerships(id) ON DELETE CASCADE,
  provider_type text NOT NULL CHECK (provider_type IN ('inventory_import', 'vehicle_data', 'media_publishing', 'inventory_publishing')),
  provider_key text NOT NULL CHECK (provider_key ~ '^[a-z][a-z0-9_.-]{1,79}$'),
  display_name text NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 160),
  status text NOT NULL DEFAULT 'not_configured'
    CHECK (status IN ('not_configured', 'disabled', 'ready', 'syncing', 'healthy', 'failed')),
  external_dealership_id text,
  configuration_metadata jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(configuration_metadata) = 'object' AND octet_length(configuration_metadata::text) <= 65536),
  last_sync_at timestamptz,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, dealership_id, provider_type, provider_key)
);

CREATE INDEX integration_connections_status_idx
  ON public.integration_connections (organization_id, dealership_id, status, updated_at DESC);

CREATE TABLE public.vehicle_publications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id uuid NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  integration_connection_id uuid NOT NULL REFERENCES public.integration_connections(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'publishing', 'published', 'failed', 'disabled')),
  external_vehicle_id text,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error_code text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (vehicle_id, integration_connection_id)
);

CREATE INDEX vehicle_publications_status_idx
  ON public.vehicle_publications (integration_connection_id, status, updated_at DESC);

CREATE OR REPLACE FUNCTION private.record_activity(
  _dealership_id uuid,
  _vehicle_id uuid,
  _photo_shoot_id uuid,
  _actor_id uuid,
  _event_type text,
  _description text,
  _metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS public.activity_events
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  organization_id uuid;
  result public.activity_events;
BEGIN
  SELECT d.organization_id INTO organization_id
  FROM public.dealerships AS d WHERE d.id = _dealership_id;
  IF organization_id IS NULL THEN
    RAISE EXCEPTION 'Dealership is unavailable.' USING ERRCODE = 'P0002';
  END IF;
  INSERT INTO public.activity_events
    (organization_id, dealership_id, vehicle_id, photo_shoot_id,
     actor_profile_id, event_type, description, metadata)
  VALUES
    (organization_id, _dealership_id, _vehicle_id, _photo_shoot_id,
     _actor_id, _event_type, _description, coalesce(_metadata, '{}'::jsonb))
  RETURNING * INTO result;
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION private.create_shoot_payout(
  _session public.photo_capture_sessions,
  _activity_event_id bigint
)
RETURNS public.payout_entries
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  rule public.payout_rules;
  store public.dealerships;
  result public.payout_entries;
  task text := CASE WHEN _session.shoot_type = 'reshoot' THEN 'reshoot' ELSE 'photo_shoot' END;
BEGIN
  IF _session.completed_by IS NULL THEN RETURN NULL; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.profile_dealerships AS pd
    WHERE pd.profile_id = _session.completed_by
      AND pd.dealership_id = _session.dealership_id
      AND pd.payout_eligible
  ) THEN RETURN NULL; END IF;

  SELECT * INTO rule FROM public.payout_rules AS pr
  WHERE pr.dealership_id = _session.dealership_id
    AND pr.task_type = task AND pr.active
    AND pr.effective_from <= _session.completed_at::date
    AND (pr.effective_to IS NULL OR pr.effective_to >= _session.completed_at::date)
  ORDER BY pr.effective_from DESC, pr.version DESC LIMIT 1;
  IF rule.id IS NULL THEN RETURN NULL; END IF;
  SELECT * INTO store FROM public.dealerships WHERE id = _session.dealership_id;

  INSERT INTO public.payout_entries
    (dealership_id, organization_id, employee_id, vehicle_id, photo_shoot_id,
     activity_event_id, task_type, work_date, amount, rule_id, rule_snapshot)
  VALUES
    (_session.dealership_id, store.organization_id, _session.completed_by,
     _session.vehicle_id, _session.id, _activity_event_id, task,
     _session.completed_at::date, rule.amount, rule.id,
     jsonb_build_object('rule_id', rule.id, 'name', rule.name, 'version', rule.version,
                        'task_type', rule.task_type, 'amount', rule.amount,
                        'currency', 'USD', 'config', rule.config))
  ON CONFLICT (photo_shoot_id, task_type) WHERE photo_shoot_id IS NOT NULL AND status <> 'void'
  DO NOTHING
  RETURNING * INTO result;
  RETURN result;
END;
$$;

-- Completion remains an idempotent, row-locked transition. It snapshots the
-- production counts used by reports and payout calculations.
CREATE OR REPLACE FUNCTION public.complete_photo_capture_session(_session_id uuid)
RETURNS public.photo_capture_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id uuid := (SELECT auth.uid());
  target public.photo_capture_sessions;
  event public.activity_events;
BEGIN
  SELECT * INTO target FROM public.photo_capture_sessions
  WHERE id = _session_id FOR UPDATE;
  IF target.id IS NULL OR NOT private.current_user_can_mutate_capture_session(target.id) THEN
    RAISE EXCEPTION 'Capture session is unavailable.' USING ERRCODE = '42501';
  END IF;
  IF target.status IN ('completed','prepared') THEN RETURN target; END IF;

  IF target.mode = 'bulk' THEN
    SELECT count(*), 0, count(*) FILTER (WHERE lower(coalesce(shot_type,'')) IN ('front','rear','driver side','passenger side','front 3/4','rear 3/4','wheel','engine bay')),
           count(*) FILTER (WHERE lower(coalesce(shot_type,'')) LIKE '%interior%'),
           count(*) FILTER (
             WHERE lower(coalesce(shot_type,'')) NOT IN ('front','rear','driver side','passenger side','front 3/4','rear 3/4','wheel','engine bay')
               AND lower(coalesce(shot_type,'')) NOT LIKE '%interior%'
           )
    INTO target.photo_count, target.video_count, target.exterior_count, target.interior_count, target.detail_count
    FROM public.bulk_photo_items WHERE session_id = target.id;
  ELSE
    SELECT count(*) FILTER (WHERE media_kind = 'photo'),
           count(*) FILTER (WHERE media_kind = 'video'),
           count(*) FILTER (WHERE media_category = 'exterior'),
           count(*) FILTER (WHERE media_category = 'interior'),
           count(*) FILTER (WHERE media_category = 'detail')
    INTO target.photo_count, target.video_count, target.exterior_count, target.interior_count, target.detail_count
    FROM public.photos WHERE capture_session_id = target.id;
  END IF;
  IF target.photo_count + target.video_count < 1 THEN
    RAISE EXCEPTION 'Capture at least one media item before completing this session.' USING ERRCODE = '23514';
  END IF;

  UPDATE public.photo_capture_sessions
  SET status = 'completed', completed_by = actor_id, completed_at = now(),
      duration_seconds = greatest(0, extract(epoch FROM (now() - started_at))::integer),
      photo_count = target.photo_count, video_count = target.video_count,
      exterior_count = target.exterior_count, interior_count = target.interior_count,
      detail_count = target.detail_count, review_status = 'awaiting_review', updated_at = now()
  WHERE id = target.id RETURNING * INTO target;

  SELECT * INTO event FROM private.record_activity(
    target.dealership_id, target.vehicle_id, target.id, actor_id,
    CASE target.mode WHEN 'bulk' THEN 'bulk_photo_session.completed' ELSE 'photo_shoot.completed' END,
    CASE target.mode WHEN 'bulk' THEN 'Bulk photo package completed' ELSE 'Vehicle photo shoot completed' END,
    jsonb_build_object('photo_count', target.photo_count, 'video_count', target.video_count,
                       'duration_seconds', target.duration_seconds, 'shoot_type', target.shoot_type)
  );
  PERFORM private.create_shoot_payout(target, event.id);

  INSERT INTO public.audit_events (event_type, actor_profile_id, dealership_id, payload)
  VALUES (CASE target.mode WHEN 'bulk' THEN 'bulk_photo_session.completed' ELSE 'photo_session.completed' END,
          actor_id, target.dealership_id,
          jsonb_build_object('capture_session_id', target.id, 'vehicle_id', target.vehicle_id,
                             'photo_count', target.photo_count, 'duration_seconds', target.duration_seconds));
  IF target.vehicle_id IS NOT NULL THEN PERFORM private.evaluate_vehicle_readiness(target.vehicle_id); END IF;
  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_payout_status(
  _payout_id uuid,
  _status text
)
RETURNS public.payout_entries
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id uuid := (SELECT auth.uid());
  target public.payout_entries;
BEGIN
  SELECT * INTO target FROM public.payout_entries WHERE id = _payout_id FOR UPDATE;
  IF target.id IS NULL OR NOT private.current_user_has_store_capability(target.dealership_id, 'payout_status') THEN
    RAISE EXCEPTION 'Payout is unavailable.' USING ERRCODE = '42501';
  END IF;
  IF _status NOT IN ('approved','paid','void') THEN
    RAISE EXCEPTION 'Unsupported payout status.' USING ERRCODE = '22023';
  END IF;
  IF target.status = 'paid' THEN
    RAISE EXCEPTION 'Paid entries are immutable.' USING ERRCODE = '55000';
  END IF;

  UPDATE public.payout_entries
  SET status = _status,
      approved_by = CASE WHEN _status IN ('approved','paid') THEN coalesce(approved_by, actor_id) ELSE approved_by END,
      approved_at = CASE WHEN _status IN ('approved','paid') THEN coalesce(approved_at, now()) ELSE approved_at END,
      paid_by = CASE WHEN _status = 'paid' THEN actor_id ELSE NULL END,
      paid_at = CASE WHEN _status = 'paid' THEN now() ELSE NULL END,
      updated_at = now()
  WHERE id = target.id RETURNING * INTO target;

  INSERT INTO public.audit_events (event_type, actor_profile_id, dealership_id, payload)
  VALUES ('payout.status_changed', actor_id, target.dealership_id,
          jsonb_build_object('payout_id', target.id, 'status', target.status,
                             'employee_id', target.employee_id, 'amount', target.amount));
  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION private.record_vehicle_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  event_name text;
  event_description text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    event_name := 'vehicle.created';
    event_description := 'Vehicle added to inventory';
  ELSIF OLD.assigned_photographer_id IS DISTINCT FROM NEW.assigned_photographer_id THEN
    event_name := 'vehicle.photographer_assigned';
    event_description := 'Vehicle photographer assignment changed';
  ELSIF OLD.retail_readiness_status IS DISTINCT FROM NEW.retail_readiness_status THEN
    event_name := 'vehicle.readiness_changed';
    event_description := 'Vehicle readiness changed to ' || replace(NEW.retail_readiness_status, '_', ' ');
  ELSE
    event_name := 'vehicle.data_updated';
    event_description := 'Vehicle merchandising data updated';
  END IF;

  PERFORM private.record_activity(
    NEW.dealership_id,
    NEW.id,
    NULL,
    (SELECT auth.uid()),
    event_name,
    event_description,
    jsonb_build_object(
      'stock_number', NEW.stock_number,
      'vin', NEW.vin,
      'readiness_status', NEW.retail_readiness_status
    )
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION private.record_photo_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target public.photos%ROWTYPE := CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  store_id uuid;
  session_actor uuid;
BEGIN
  SELECT dealership_id INTO store_id FROM public.vehicles WHERE id = target.vehicle_id;
  SELECT created_by INTO session_actor
  FROM public.photo_capture_sessions WHERE id = target.capture_session_id;
  PERFORM private.record_activity(
    store_id, target.vehicle_id, target.capture_session_id,
    coalesce((SELECT auth.uid()), session_actor),
    CASE WHEN TG_OP = 'DELETE' THEN 'photo.removed' ELSE 'photo.uploaded' END,
    CASE WHEN TG_OP = 'DELETE' THEN 'Photo removed' ELSE 'Original photo uploaded' END,
    jsonb_build_object('photo_id', target.id, 'media_kind', target.media_kind,
                       'media_category', target.media_category, 'shot_type', target.shot_type)
  );
  RETURN target;
END;
$$;

CREATE OR REPLACE FUNCTION private.record_document_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM private.record_activity(
    NEW.dealership_id, NEW.vehicle_id, NULL, NEW.generated_by,
    'vehicle_document.generated', 'Vehicle document generated',
    jsonb_build_object('document_id', NEW.id, 'document_type', NEW.document_type,
                       'template_version', NEW.template_version)
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION private.record_media_variant_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target_vehicle uuid;
  store_id uuid;
BEGIN
  IF NEW.variant_type = 'original' THEN RETURN NEW; END IF;
  SELECT p.vehicle_id, v.dealership_id INTO target_vehicle, store_id
  FROM public.photos AS p JOIN public.vehicles AS v ON v.id = p.vehicle_id
  WHERE p.id = NEW.photo_id;
  PERFORM private.record_activity(
    store_id, target_vehicle, NULL, NEW.created_by,
    'vehicle_media.variant_created', 'Prepared media variant created',
    jsonb_build_object('photo_id', NEW.photo_id, 'variant_id', NEW.id,
                       'variant_type', NEW.variant_type,
                       'processing_provider', NEW.processing_provider)
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER vehicles_record_operational_activity
AFTER INSERT OR UPDATE OF vin, stock_number, year, make, model, trim, price,
  msrp, internet_price, sale_price, comments, custom_comments,
  publication_description, assigned_photographer_id, retail_readiness_status
ON public.vehicles FOR EACH ROW EXECUTE FUNCTION private.record_vehicle_activity();

CREATE TRIGGER photos_record_operational_activity
AFTER INSERT OR DELETE ON public.photos
FOR EACH ROW EXECUTE FUNCTION private.record_photo_activity();
CREATE TRIGGER generated_documents_record_operational_activity
AFTER INSERT ON public.generated_documents
FOR EACH ROW EXECUTE FUNCTION private.record_document_activity();
CREATE TRIGGER media_variants_record_operational_activity
AFTER INSERT ON public.media_variants
FOR EACH ROW EXECUTE FUNCTION private.record_media_variant_activity();

CREATE OR REPLACE FUNCTION public.create_payout_rule(
  _dealership_id uuid,
  _name text,
  _task_type text,
  _amount numeric,
  _effective_from date DEFAULT CURRENT_DATE,
  _config jsonb DEFAULT '{}'::jsonb
)
RETURNS public.payout_rules
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id uuid := (SELECT auth.uid());
  next_version integer;
  result public.payout_rules;
BEGIN
  IF NOT private.current_user_has_store_capability(_dealership_id, 'settings') THEN
    RAISE EXCEPTION 'Payout settings are unavailable.' USING ERRCODE = '42501';
  END IF;
  IF _task_type NOT IN ('photo_shoot','video','exterior_360','interior_360','reshoot','audit','manual')
     OR _amount < 0 OR nullif(btrim(_name), '') IS NULL THEN
    RAISE EXCEPTION 'Invalid payout rule.' USING ERRCODE = '22023';
  END IF;

  SELECT coalesce(max(version), 0) + 1 INTO next_version
  FROM public.payout_rules
  WHERE dealership_id = _dealership_id AND task_type = _task_type;

  UPDATE public.payout_rules SET active = false
  WHERE dealership_id = _dealership_id AND task_type = _task_type AND active;

  INSERT INTO public.payout_rules
    (dealership_id, name, task_type, amount, version, effective_from,
     config, created_by)
  VALUES
    (_dealership_id, btrim(_name), _task_type, _amount, next_version,
     _effective_from, coalesce(_config, '{}'::jsonb), actor_id)
  RETURNING * INTO result;

  INSERT INTO public.audit_events (event_type, actor_profile_id, dealership_id, payload)
  VALUES ('payout.rule_created', actor_id, _dealership_id,
          jsonb_build_object('rule_id', result.id, 'task_type', result.task_type,
                             'version', result.version, 'amount', result.amount));
  RETURN result;
END;
$$;

ALTER TABLE public.activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integration_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_publications ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.activity_events, public.payout_rules, public.payout_entries,
  public.integration_connections, public.vehicle_publications
FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.activity_events_id_seq FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.activity_events, public.payout_rules, public.payout_entries,
  public.integration_connections, public.vehicle_publications TO authenticated;
GRANT ALL ON public.activity_events, public.payout_rules, public.payout_entries,
  public.integration_connections, public.vehicle_publications TO service_role;
GRANT ALL ON SEQUENCE public.activity_events_id_seq TO service_role;

CREATE POLICY "Authorized users view operational activity"
ON public.activity_events FOR SELECT TO authenticated
USING (
  private.current_user_has_store_capability(dealership_id, 'reports')
  OR (actor_profile_id = (SELECT auth.uid()) AND private.current_user_has_active_membership(dealership_id))
);
CREATE POLICY "Authorized users view payout rules"
ON public.payout_rules FOR SELECT TO authenticated
USING (private.current_user_has_store_capability(dealership_id, 'reports'));
CREATE POLICY "Authorized users view payout entries"
ON public.payout_entries FOR SELECT TO authenticated
USING (
  private.current_user_has_store_capability(dealership_id, 'reports')
  OR (employee_id = (SELECT auth.uid()) AND private.current_user_has_store_capability(dealership_id, 'self_reports'))
);
CREATE POLICY "Administrators view integration status"
ON public.integration_connections FOR SELECT TO authenticated
USING (
  private.current_user_is_active_owner()
  OR (dealership_id IS NOT NULL AND private.current_user_has_store_capability(dealership_id, 'settings'))
);
CREATE POLICY "Active members view vehicle publication status"
ON public.vehicle_publications FOR SELECT TO authenticated
USING (private.current_user_can_access_vehicle(vehicle_id));

REVOKE ALL ON FUNCTION private.record_activity(uuid, uuid, uuid, uuid, text, text, jsonb)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.create_shoot_payout(public.photo_capture_sessions, bigint)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.record_vehicle_activity()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.record_photo_activity()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.record_document_activity()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.record_media_variant_activity()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.set_payout_status(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_payout_rule(uuid, text, text, numeric, date, jsonb)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_payout_status(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.create_payout_rule(uuid, text, text, numeric, date, jsonb)
  TO authenticated, service_role;

-- Existing completion function remains directly callable by authenticated users
-- because it derives actor identity and verifies the locked target session.
REVOKE ALL ON FUNCTION public.complete_photo_capture_session(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.complete_photo_capture_session(uuid) TO authenticated, service_role;
